// Modals
export const MODAL_CONTACTS_US = "MODAL_CONTACTS_US";
export const MODAL_LETS_CHAT = "MODAL_LETS_CHAT";
export const MODAL_REQUEST_QUOTE = "MODAL_REQUEST_QUOTE";
export const MODAL_SERVICE = "MODAL_SERVICE";
export const MODAL_TECHNOLOGIES = "MODAL_TECHNOLOGIES"